// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewIT.DataAccess;

namespace ReviewIT.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("ReviewIT.DataAccess.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Apple",
                            Description = "Who is  the superior brand?",
                            ImagePath = "/Brand_Apple.png"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Samsung",
                            Description = "Obviously, I am the superior brand",
                            ImagePath = "/Brand_Samsung.jpg"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Google",
                            Description = "Nope, I am obviously better.",
                            ImagePath = "/Brand_Google.jpg"
                        });
                });

            modelBuilder.Entity("ReviewIT.DataAccess.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CommentId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommentId");

                    b.HasIndex("CommentId1");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 7155,
                            CommentContent = @"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.
Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
                            CreationDate = new DateTime(2019, 6, 15, 6, 23, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "63062",
                            IsArchived = false,
                            PostId = 1
                        },
                        new
                        {
                            CommentId = 48229,
                            CommentContent = @"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.
Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.
Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
                            CreationDate = new DateTime(2018, 5, 9, 6, 23, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "83912",
                            IsArchived = false,
                            ParentCommentId = 7155,
                            PostId = 1
                        },
                        new
                        {
                            CommentId = 55854,
                            CommentContent = @"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.
In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.
Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
                            CreationDate = new DateTime(2020, 5, 6, 16, 46, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "77416",
                            IsArchived = false,
                            ParentCommentId = 7155,
                            PostId = 1
                        },
                        new
                        {
                            CommentId = 87232,
                            CommentContent = "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
                            CreationDate = new DateTime(2020, 6, 11, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "67706",
                            IsArchived = false,
                            ParentCommentId = 48229,
                            PostId = 1
                        },
                        new
                        {
                            CommentId = 9541,
                            CommentContent = "Fusce consequat. Nulla nisl. Nunc nisl.",
                            CreationDate = new DateTime(2020, 4, 16, 20, 28, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "42923",
                            IsArchived = false,
                            ParentCommentId = 55854,
                            PostId = 1
                        },
                        new
                        {
                            CommentId = 33112,
                            CommentContent = "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
                            CreationDate = new DateTime(2020, 5, 22, 7, 49, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "67706",
                            IsArchived = false,
                            PostId = 2
                        },
                        new
                        {
                            CommentId = 27571,
                            CommentContent = @"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.
Fusce consequat. Nulla nisl. Nunc nisl.
Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
                            CreationDate = new DateTime(2020, 3, 1, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "77416",
                            IsArchived = false,
                            ParentCommentId = 33112,
                            PostId = 2
                        },
                        new
                        {
                            CommentId = 62852,
                            CommentContent = @"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.
Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
                            CreationDate = new DateTime(2019, 8, 3, 22, 21, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "83912",
                            IsArchived = false,
                            ParentCommentId = 27571,
                            PostId = 2
                        },
                        new
                        {
                            CommentId = 43195,
                            CommentContent = @"In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.
Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.
Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
                            CreationDate = new DateTime(2021, 2, 5, 16, 29, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "67706",
                            IsArchived = false,
                            ParentCommentId = 62852,
                            PostId = 2
                        },
                        new
                        {
                            CommentId = 47216,
                            CommentContent = @"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.
Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
                            CreationDate = new DateTime(2020, 4, 19, 4, 10, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "67588",
                            IsArchived = false,
                            ParentCommentId = 43195,
                            PostId = 2
                        },
                        new
                        {
                            CommentId = 62903,
                            CommentContent = @"In congue. Etiam justo. Etiam pretium iaculis justo.
In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.
Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
                            CreationDate = new DateTime(2018, 5, 27, 12, 48, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "63062",
                            IsArchived = false,
                            PostId = 3
                        },
                        new
                        {
                            CommentId = 56806,
                            CommentContent = @"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.
Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.
Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
                            CreationDate = new DateTime(2018, 10, 30, 3, 57, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "73398",
                            IsArchived = false,
                            ParentCommentId = 62903,
                            PostId = 3
                        },
                        new
                        {
                            CommentId = 53822,
                            CommentContent = @"In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.
Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
                            CreationDate = new DateTime(2021, 1, 5, 1, 46, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "73398",
                            IsArchived = false,
                            ParentCommentId = 62903,
                            PostId = 3
                        },
                        new
                        {
                            CommentId = 66609,
                            CommentContent = "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
                            CreationDate = new DateTime(2019, 10, 5, 6, 2, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "67588",
                            IsArchived = false,
                            ParentCommentId = 56806,
                            PostId = 3
                        },
                        new
                        {
                            CommentId = 75077,
                            CommentContent = @"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.
Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
                            CreationDate = new DateTime(2020, 10, 25, 23, 47, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "83912",
                            IsArchived = false,
                            PostId = 4
                        },
                        new
                        {
                            CommentId = 72706,
                            CommentContent = @"In congue. Etiam justo. Etiam pretium iaculis justo.
In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
                            CreationDate = new DateTime(2020, 7, 8, 3, 18, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "4345",
                            IsArchived = false,
                            ParentCommentId = 75077,
                            PostId = 4
                        },
                        new
                        {
                            CommentId = 44515,
                            CommentContent = @"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.
Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.
Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
                            CreationDate = new DateTime(2018, 7, 11, 5, 26, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "63062",
                            IsArchived = false,
                            ParentCommentId = 72706,
                            PostId = 4
                        },
                        new
                        {
                            CommentId = 60624,
                            CommentContent = @"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.
Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.
Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
                            CreationDate = new DateTime(2020, 1, 14, 6, 37, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "6561",
                            IsArchived = false,
                            PostId = 5
                        },
                        new
                        {
                            CommentId = 8832,
                            CommentContent = "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
                            CreationDate = new DateTime(2018, 2, 28, 21, 26, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "21564",
                            IsArchived = false,
                            ParentCommentId = 60624,
                            PostId = 5
                        },
                        new
                        {
                            CommentId = 80156,
                            CommentContent = "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
                            CreationDate = new DateTime(2019, 8, 15, 16, 19, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "78347",
                            IsArchived = false,
                            ParentCommentId = 8832,
                            PostId = 5
                        },
                        new
                        {
                            CommentId = 5500,
                            CommentContent = @"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.
Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
                            CreationDate = new DateTime(2019, 6, 10, 22, 43, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "21564",
                            IsArchived = false,
                            PostId = 6
                        },
                        new
                        {
                            CommentId = 43501,
                            CommentContent = @"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.
In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.
Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
                            CreationDate = new DateTime(2020, 5, 22, 5, 15, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "6561",
                            IsArchived = false,
                            ParentCommentId = 5500,
                            PostId = 6
                        },
                        new
                        {
                            CommentId = 61911,
                            CommentContent = @"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.
In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
                            CreationDate = new DateTime(2019, 3, 13, 2, 31, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "21564",
                            IsArchived = false,
                            ParentCommentId = 5500,
                            PostId = 6
                        },
                        new
                        {
                            CommentId = 15907,
                            CommentContent = @"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.
Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
                            CreationDate = new DateTime(2020, 12, 24, 3, 32, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "63062",
                            IsArchived = false,
                            ParentCommentId = 5500,
                            PostId = 6
                        },
                        new
                        {
                            CommentId = 5399,
                            CommentContent = "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
                            CreationDate = new DateTime(2020, 9, 29, 21, 47, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "21564",
                            IsArchived = false,
                            ParentCommentId = 43501,
                            PostId = 6
                        },
                        new
                        {
                            CommentId = 52881,
                            CommentContent = "Fusce consequat. Nulla nisl. Nunc nisl.",
                            CreationDate = new DateTime(2019, 6, 28, 19, 22, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "85497",
                            IsArchived = false,
                            ParentCommentId = 43501,
                            PostId = 6
                        },
                        new
                        {
                            CommentId = 5159,
                            CommentContent = @"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.
Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.
Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
                            CreationDate = new DateTime(2018, 9, 6, 10, 32, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "78347",
                            IsArchived = false,
                            PostId = 7
                        },
                        new
                        {
                            CommentId = 81677,
                            CommentContent = @"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.
Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
                            CreationDate = new DateTime(2019, 7, 7, 0, 23, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "79354",
                            IsArchived = false,
                            ParentCommentId = 5159,
                            PostId = 7
                        },
                        new
                        {
                            CommentId = 74034,
                            CommentContent = @"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.
Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
                            CreationDate = new DateTime(2020, 2, 25, 13, 47, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "85497",
                            IsArchived = false,
                            ParentCommentId = 5159,
                            PostId = 7
                        },
                        new
                        {
                            CommentId = 17963,
                            CommentContent = "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
                            CreationDate = new DateTime(2018, 4, 9, 12, 55, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "61437",
                            IsArchived = false,
                            PostId = 8
                        },
                        new
                        {
                            CommentId = 25133,
                            CommentContent = "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
                            CreationDate = new DateTime(2019, 12, 12, 16, 22, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "42923",
                            IsArchived = false,
                            ParentCommentId = 17963,
                            PostId = 8
                        },
                        new
                        {
                            CommentId = 77379,
                            CommentContent = "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
                            CreationDate = new DateTime(2018, 3, 22, 12, 27, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "26600",
                            IsArchived = false,
                            ParentCommentId = 17963,
                            PostId = 8
                        },
                        new
                        {
                            CommentId = 15986,
                            CommentContent = @"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.
Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.
Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
                            CreationDate = new DateTime(2019, 4, 5, 19, 4, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "61437",
                            IsArchived = false,
                            ParentCommentId = 25133,
                            PostId = 8
                        },
                        new
                        {
                            CommentId = 46382,
                            CommentContent = "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
                            CreationDate = new DateTime(2018, 9, 8, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "42923",
                            IsArchived = false,
                            PostId = 9
                        },
                        new
                        {
                            CommentId = 66096,
                            CommentContent = @"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.
Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
                            CreationDate = new DateTime(2020, 5, 18, 17, 29, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "26600",
                            IsArchived = false,
                            ParentCommentId = 46382,
                            PostId = 9
                        },
                        new
                        {
                            CommentId = 16852,
                            CommentContent = "Fusce consequat. Nulla nisl. Nunc nisl.",
                            CreationDate = new DateTime(2019, 12, 4, 18, 11, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "79354",
                            IsArchived = false,
                            ParentCommentId = 46382,
                            PostId = 9
                        },
                        new
                        {
                            CommentId = 51175,
                            CommentContent = "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
                            CreationDate = new DateTime(2020, 7, 18, 18, 14, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "67588",
                            IsArchived = false,
                            ParentCommentId = 16852,
                            PostId = 9
                        },
                        new
                        {
                            CommentId = 71712,
                            CommentContent = @"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.
Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
                            CreationDate = new DateTime(2018, 6, 17, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "67588",
                            IsArchived = false,
                            ParentCommentId = 51175,
                            PostId = 9
                        });
                });

            modelBuilder.Entity("ReviewIT.DataAccess.CommentVote", b =>
                {
                    b.Property<int>("CommentVoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("CommentVoteId");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentVotes");

                    b.HasData(
                        new
                        {
                            CommentVoteId = 62563,
                            CommentId = 7155,
                            CreationDate = new DateTime(2018, 7, 23, 20, 22, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "63062"
                        },
                        new
                        {
                            CommentVoteId = 26760,
                            CommentId = 48229,
                            CreationDate = new DateTime(2019, 10, 17, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "83912"
                        },
                        new
                        {
                            CommentVoteId = 31394,
                            CommentId = 55854,
                            CreationDate = new DateTime(2019, 9, 1, 15, 5, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "63062"
                        },
                        new
                        {
                            CommentVoteId = 50312,
                            CommentId = 87232,
                            CreationDate = new DateTime(2018, 6, 21, 19, 8, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "77416"
                        },
                        new
                        {
                            CommentVoteId = 14200,
                            CommentId = 9541,
                            CreationDate = new DateTime(2019, 7, 25, 15, 49, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "83912"
                        },
                        new
                        {
                            CommentVoteId = 42574,
                            CommentId = 33112,
                            CreationDate = new DateTime(2020, 12, 5, 23, 4, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "42923"
                        },
                        new
                        {
                            CommentVoteId = 24309,
                            CommentId = 27571,
                            CreationDate = new DateTime(2020, 12, 29, 0, 4, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "83912"
                        },
                        new
                        {
                            CommentVoteId = 89339,
                            CommentId = 62852,
                            CreationDate = new DateTime(2019, 6, 26, 4, 36, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "21564"
                        },
                        new
                        {
                            CommentVoteId = 48135,
                            CommentId = 43195,
                            CreationDate = new DateTime(2019, 3, 19, 8, 54, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "42923"
                        },
                        new
                        {
                            CommentVoteId = 64023,
                            CommentId = 47216,
                            CreationDate = new DateTime(2018, 11, 18, 7, 28, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "83912"
                        },
                        new
                        {
                            CommentVoteId = 67785,
                            CommentId = 62903,
                            CreationDate = new DateTime(2019, 11, 12, 15, 49, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "6561"
                        },
                        new
                        {
                            CommentVoteId = 52972,
                            CommentId = 56806,
                            CreationDate = new DateTime(2018, 4, 29, 14, 24, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "63062"
                        },
                        new
                        {
                            CommentVoteId = 82330,
                            CommentId = 53822,
                            CreationDate = new DateTime(2018, 10, 1, 5, 14, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "6561"
                        },
                        new
                        {
                            CommentVoteId = 76289,
                            CommentId = 66609,
                            CreationDate = new DateTime(2019, 6, 21, 16, 11, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "42923"
                        },
                        new
                        {
                            CommentVoteId = 28431,
                            CommentId = 75077,
                            CreationDate = new DateTime(2018, 11, 14, 6, 29, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "4345"
                        },
                        new
                        {
                            CommentVoteId = 75814,
                            CommentId = 72706,
                            CreationDate = new DateTime(2020, 8, 12, 4, 33, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "73398"
                        },
                        new
                        {
                            CommentVoteId = 72701,
                            CommentId = 44515,
                            CreationDate = new DateTime(2020, 5, 8, 14, 17, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "6561"
                        },
                        new
                        {
                            CommentVoteId = 64607,
                            CommentId = 60624,
                            CreationDate = new DateTime(2021, 1, 12, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "83912"
                        },
                        new
                        {
                            CommentVoteId = 32387,
                            CommentId = 8832,
                            CreationDate = new DateTime(2019, 12, 22, 6, 48, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "67588"
                        },
                        new
                        {
                            CommentVoteId = 25805,
                            CommentId = 80156,
                            CreationDate = new DateTime(2019, 10, 17, 22, 51, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "4345"
                        },
                        new
                        {
                            CommentVoteId = 62706,
                            CommentId = 5500,
                            CreationDate = new DateTime(2020, 10, 6, 22, 26, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "67588"
                        },
                        new
                        {
                            CommentVoteId = 37575,
                            CommentId = 43501,
                            CreationDate = new DateTime(2021, 2, 8, 23, 2, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "83912"
                        },
                        new
                        {
                            CommentVoteId = 20541,
                            CommentId = 61911,
                            CreationDate = new DateTime(2018, 8, 25, 17, 31, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "61437"
                        },
                        new
                        {
                            CommentVoteId = 37291,
                            CommentId = 15907,
                            CreationDate = new DateTime(2018, 3, 2, 3, 45, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "4345"
                        },
                        new
                        {
                            CommentVoteId = 20999,
                            CommentId = 5399,
                            CreationDate = new DateTime(2021, 2, 14, 3, 55, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "42923"
                        },
                        new
                        {
                            CommentVoteId = 57672,
                            CommentId = 52881,
                            CreationDate = new DateTime(2018, 6, 21, 12, 22, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "78347"
                        },
                        new
                        {
                            CommentVoteId = 62190,
                            CommentId = 5159,
                            CreationDate = new DateTime(2020, 7, 29, 11, 12, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "26600"
                        },
                        new
                        {
                            CommentVoteId = 35519,
                            CommentId = 81677,
                            CreationDate = new DateTime(2020, 6, 8, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "77416"
                        },
                        new
                        {
                            CommentVoteId = 78546,
                            CommentId = 74034,
                            CreationDate = new DateTime(2019, 9, 23, 10, 39, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "78347"
                        },
                        new
                        {
                            CommentVoteId = 88693,
                            CommentId = 17963,
                            CreationDate = new DateTime(2019, 4, 22, 17, 3, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "79354"
                        },
                        new
                        {
                            CommentVoteId = 55617,
                            CommentId = 25133,
                            CreationDate = new DateTime(2018, 5, 22, 17, 8, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "77416"
                        },
                        new
                        {
                            CommentVoteId = 22185,
                            CommentId = 77379,
                            CreationDate = new DateTime(2020, 7, 12, 5, 8, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "26600"
                        },
                        new
                        {
                            CommentVoteId = 78543,
                            CommentId = 15986,
                            CreationDate = new DateTime(2018, 4, 14, 23, 11, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "79354"
                        },
                        new
                        {
                            CommentVoteId = 73781,
                            CommentId = 46382,
                            CreationDate = new DateTime(2018, 6, 25, 0, 14, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "77416"
                        },
                        new
                        {
                            CommentVoteId = 51272,
                            CommentId = 66096,
                            CreationDate = new DateTime(2018, 5, 5, 22, 43, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "61437"
                        },
                        new
                        {
                            CommentVoteId = 16966,
                            CommentId = 16852,
                            CreationDate = new DateTime(2018, 6, 27, 20, 2, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "78347"
                        },
                        new
                        {
                            CommentVoteId = 39316,
                            CommentId = 51175,
                            CreationDate = new DateTime(2019, 7, 27, 2, 59, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            UserId = "79354"
                        },
                        new
                        {
                            CommentVoteId = 41021,
                            CommentId = 71712,
                            CreationDate = new DateTime(2018, 12, 31, 1, 30, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            UserId = "85497"
                        });
                });

            modelBuilder.Entity("ReviewIT.DataAccess.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatingForDevice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            CreationDate = new DateTime(2018, 11, 22, 21, 1, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "63062",
                            IsArchived = false,
                            PostContent = @"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.
Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
                            ProductId = 1,
                            RatingForDevice = 1,
                            Title = "eget congue eget semper rutrum nulla nunc purus phasellus in felis"
                        },
                        new
                        {
                            PostId = 2,
                            CreationDate = new DateTime(2018, 12, 4, 1, 51, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "83912",
                            IsArchived = false,
                            PostContent = "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
                            ProductId = 2,
                            RatingForDevice = 5,
                            Title = "nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat"
                        },
                        new
                        {
                            PostId = 3,
                            CreationDate = new DateTime(2018, 4, 25, 3, 42, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "77416",
                            IsArchived = false,
                            PostContent = "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
                            ProductId = 3,
                            RatingForDevice = 5,
                            Title = "integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare"
                        },
                        new
                        {
                            PostId = 4,
                            CreationDate = new DateTime(2018, 6, 27, 10, 9, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "42923",
                            IsArchived = false,
                            PostContent = @"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.
Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.
Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
                            ProductId = 4,
                            RatingForDevice = 0,
                            Title = "habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at"
                        },
                        new
                        {
                            PostId = 5,
                            CreationDate = new DateTime(2018, 11, 20, 19, 25, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "79354",
                            IsArchived = false,
                            PostContent = @"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.
Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
                            ProductId = 5,
                            RatingForDevice = 3,
                            Title = "donec semper sapien a libero nam dui proin leo odio porttitor id"
                        },
                        new
                        {
                            PostId = 6,
                            CreationDate = new DateTime(2019, 5, 6, 17, 46, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "78347",
                            IsArchived = false,
                            PostContent = "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
                            ProductId = 6,
                            RatingForDevice = 0,
                            Title = "elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at"
                        },
                        new
                        {
                            PostId = 7,
                            CreationDate = new DateTime(2020, 1, 20, 22, 50, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "6561",
                            IsArchived = false,
                            PostContent = "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
                            ProductId = 7,
                            RatingForDevice = 4,
                            Title = "suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut"
                        },
                        new
                        {
                            PostId = 8,
                            CreationDate = new DateTime(2021, 2, 5, 20, 57, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "4345",
                            IsArchived = false,
                            PostContent = "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
                            ProductId = 8,
                            RatingForDevice = 4,
                            Title = "nulla suspendisse potenti cras in purus eu magna vulputate luctus cum"
                        },
                        new
                        {
                            PostId = 9,
                            CreationDate = new DateTime(2019, 11, 3, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            CreatorUserId = "67588",
                            IsArchived = false,
                            PostContent = @"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.
Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.
Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
                            ProductId = 9,
                            RatingForDevice = 2,
                            Title = "orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae"
                        });
                });

            modelBuilder.Entity("ReviewIT.DataAccess.PostVote", b =>
                {
                    b.Property<int>("PostVoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("PostVoteId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostVotes");

                    b.HasData(
                        new
                        {
                            PostVoteId = 47995,
                            CreationDate = new DateTime(2019, 12, 26, 19, 49, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 1,
                            UserId = "63062"
                        },
                        new
                        {
                            PostVoteId = 34143,
                            CreationDate = new DateTime(2018, 12, 28, 0, 36, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 1,
                            UserId = "83912"
                        },
                        new
                        {
                            PostVoteId = 40119,
                            CreationDate = new DateTime(2018, 7, 17, 13, 29, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 1,
                            UserId = "77416"
                        },
                        new
                        {
                            PostVoteId = 37162,
                            CreationDate = new DateTime(2018, 11, 25, 5, 54, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 1,
                            UserId = "42923"
                        },
                        new
                        {
                            PostVoteId = 10544,
                            CreationDate = new DateTime(2018, 8, 1, 1, 10, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 2,
                            UserId = "79354"
                        },
                        new
                        {
                            PostVoteId = 82944,
                            CreationDate = new DateTime(2018, 3, 29, 0, 37, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 2,
                            UserId = "78347"
                        },
                        new
                        {
                            PostVoteId = 61035,
                            CreationDate = new DateTime(2019, 3, 30, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 2,
                            UserId = "6561"
                        },
                        new
                        {
                            PostVoteId = 77873,
                            CreationDate = new DateTime(2020, 1, 16, 18, 47, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 2,
                            UserId = "4345"
                        },
                        new
                        {
                            PostVoteId = 74012,
                            CreationDate = new DateTime(2020, 4, 10, 20, 52, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 3,
                            UserId = "67588"
                        },
                        new
                        {
                            PostVoteId = 1966,
                            CreationDate = new DateTime(2019, 4, 18, 19, 1, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 3,
                            UserId = "26600"
                        },
                        new
                        {
                            PostVoteId = 52786,
                            CreationDate = new DateTime(2019, 7, 30, 11, 14, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 3,
                            UserId = "61437"
                        },
                        new
                        {
                            PostVoteId = 39810,
                            CreationDate = new DateTime(2020, 9, 7, 15, 58, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 3,
                            UserId = "85497"
                        },
                        new
                        {
                            PostVoteId = 57865,
                            CreationDate = new DateTime(2020, 6, 14, 22, 51, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 4,
                            UserId = "21564"
                        },
                        new
                        {
                            PostVoteId = 77670,
                            CreationDate = new DateTime(2020, 3, 2, 16, 14, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 4,
                            UserId = "73398"
                        },
                        new
                        {
                            PostVoteId = 9873,
                            CreationDate = new DateTime(2019, 9, 9, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 4,
                            UserId = "67706"
                        },
                        new
                        {
                            PostVoteId = 84465,
                            CreationDate = new DateTime(2019, 6, 10, 23, 3, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 4,
                            UserId = "63062"
                        },
                        new
                        {
                            PostVoteId = 43453,
                            CreationDate = new DateTime(2019, 6, 24, 16, 13, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 5,
                            UserId = "83912"
                        },
                        new
                        {
                            PostVoteId = 36433,
                            CreationDate = new DateTime(2020, 6, 7, 9, 55, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 5,
                            UserId = "77416"
                        },
                        new
                        {
                            PostVoteId = 20089,
                            CreationDate = new DateTime(2020, 12, 6, 21, 13, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 5,
                            UserId = "42923"
                        },
                        new
                        {
                            PostVoteId = 42537,
                            CreationDate = new DateTime(2019, 4, 15, 22, 7, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 5,
                            UserId = "79354"
                        },
                        new
                        {
                            PostVoteId = 84847,
                            CreationDate = new DateTime(2018, 11, 12, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 6,
                            UserId = "78347"
                        },
                        new
                        {
                            PostVoteId = 46496,
                            CreationDate = new DateTime(2018, 6, 27, 20, 47, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 6,
                            UserId = "6561"
                        },
                        new
                        {
                            PostVoteId = 15615,
                            CreationDate = new DateTime(2019, 4, 21, 4, 31, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 6,
                            UserId = "4345"
                        },
                        new
                        {
                            PostVoteId = 13319,
                            CreationDate = new DateTime(2018, 8, 24, 11, 33, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 6,
                            UserId = "67588"
                        },
                        new
                        {
                            PostVoteId = 64214,
                            CreationDate = new DateTime(2020, 5, 7, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 7,
                            UserId = "26600"
                        },
                        new
                        {
                            PostVoteId = 28775,
                            CreationDate = new DateTime(2019, 1, 21, 12, 31, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 7,
                            UserId = "61437"
                        },
                        new
                        {
                            PostVoteId = 79265,
                            CreationDate = new DateTime(2020, 4, 13, 19, 20, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 7,
                            UserId = "85497"
                        },
                        new
                        {
                            PostVoteId = 74359,
                            CreationDate = new DateTime(2019, 7, 9, 7, 33, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 7,
                            UserId = "21564"
                        },
                        new
                        {
                            PostVoteId = 47030,
                            CreationDate = new DateTime(2019, 4, 13, 1, 34, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 8,
                            UserId = "73398"
                        },
                        new
                        {
                            PostVoteId = 20858,
                            CreationDate = new DateTime(2019, 8, 2, 7, 42, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 8,
                            UserId = "67706"
                        },
                        new
                        {
                            PostVoteId = 10443,
                            CreationDate = new DateTime(2018, 12, 26, 23, 34, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 8,
                            UserId = "63062"
                        },
                        new
                        {
                            PostVoteId = 85004,
                            CreationDate = new DateTime(2019, 1, 11, 21, 51, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 8,
                            UserId = "83912"
                        },
                        new
                        {
                            PostVoteId = 51984,
                            CreationDate = new DateTime(2019, 7, 7, 0, 42, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 9,
                            UserId = "77416"
                        },
                        new
                        {
                            PostVoteId = 29030,
                            CreationDate = new DateTime(2020, 1, 13, 20, 33, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = false,
                            PostId = 9,
                            UserId = "42923"
                        },
                        new
                        {
                            PostVoteId = 80709,
                            CreationDate = new DateTime(2020, 2, 2, 3, 31, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 9,
                            UserId = "79354"
                        },
                        new
                        {
                            PostVoteId = 51950,
                            CreationDate = new DateTime(2020, 2, 12, 1, 48, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 9,
                            UserId = "78347"
                        },
                        new
                        {
                            PostVoteId = 33000,
                            CreationDate = new DateTime(2020, 11, 14, 11, 44, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 9,
                            UserId = "6561"
                        },
                        new
                        {
                            PostVoteId = 28643,
                            CreationDate = new DateTime(2018, 9, 26, 0, 28, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            IsUp = true,
                            PostId = 9,
                            UserId = "4345"
                        });
                });

            modelBuilder.Entity("ReviewIT.DataAccess.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageRating")
                        .HasColumnType("REAL");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AverageRating = 0.0,
                            BrandId = 1,
                            Description = "This is fluff for now",
                            ImagePath = "/iphone12max&pro.jpg",
                            IsArchived = false,
                            Name = "iPhone 12 Pro Max",
                            Price = 1249.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 2,
                            AverageRating = 0.0,
                            BrandId = 1,
                            Description = "This is fluff for now",
                            ImagePath = "/iphone12max&pro.jpg",
                            IsArchived = false,
                            Name = "iPhone 12 Pro",
                            Price = 1149.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 3,
                            AverageRating = 0.0,
                            BrandId = 1,
                            Description = "This is fluff for now",
                            ImagePath = "/iphone12&mini.jpg",
                            IsArchived = false,
                            Name = "iPhone 12",
                            Price = 1049.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 4,
                            AverageRating = 0.0,
                            BrandId = 1,
                            Description = "This is fluff for now",
                            ImagePath = "/iphone12&mini.jpg",
                            IsArchived = false,
                            Name = "iPhone 12 mini",
                            Price = 999.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 5,
                            AverageRating = 0.0,
                            BrandId = 1,
                            Description = "This is fluff for now",
                            ImagePath = "/iphone_SE.jpg",
                            IsArchived = false,
                            Name = "iPhone SE",
                            Price = 999.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 6,
                            AverageRating = 0.0,
                            BrandId = 1,
                            Description = "This is fluff for now",
                            ImagePath = "/iphone11pro&max.jpg",
                            IsArchived = false,
                            Name = "iPhone 11 Pro Max",
                            Price = 999.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 7,
                            AverageRating = 0.0,
                            BrandId = 1,
                            Description = "This is fluff for now",
                            ImagePath = "/iphone11pro&max.jpg",
                            IsArchived = false,
                            Name = "iPhone 11 Pro",
                            Price = 849.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 8,
                            AverageRating = 0.0,
                            BrandId = 1,
                            Description = "This is fluff for now",
                            ImagePath = "/iphone11.jpg",
                            IsArchived = false,
                            Name = "iPhone 11",
                            Price = 799.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 9,
                            AverageRating = 0.0,
                            BrandId = 1,
                            Description = "This is fluff for now",
                            ImagePath = "/iphoneXR.jpg",
                            IsArchived = false,
                            Name = "iPhone XR",
                            Price = 749.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 10,
                            AverageRating = 0.0,
                            BrandId = 2,
                            Description = "This is fluff for now",
                            ImagePath = "/galaxyNote09.jpg",
                            IsArchived = false,
                            Name = "Samsung Galaxy Note 09",
                            Price = 949.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 11,
                            AverageRating = 0.0,
                            BrandId = 2,
                            Description = "This is fluff for now",
                            ImagePath = "/galaxyNote10.jpg",
                            IsArchived = false,
                            Name = "Samsung Galaxy Note 10",
                            Price = 1049.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 12,
                            AverageRating = 0.0,
                            BrandId = 2,
                            Description = "This is fluff for now",
                            ImagePath = "/galaxyNote20.jpg",
                            IsArchived = false,
                            Name = "Samsung Galaxy Note 20",
                            Price = 1149.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 13,
                            AverageRating = 0.0,
                            BrandId = 2,
                            Description = "This is fluff for now",
                            ImagePath = "/galaxyS10.jpg",
                            IsArchived = false,
                            Name = "Samsung Galaxy S10",
                            Price = 849.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 14,
                            AverageRating = 0.0,
                            BrandId = 2,
                            Description = "This is fluff for now",
                            ImagePath = "/galaxyS20.jpg",
                            IsArchived = false,
                            Name = "Samsung Galaxy S20",
                            Price = 1049.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 15,
                            AverageRating = 0.0,
                            BrandId = 2,
                            Description = "This is fluff for now",
                            ImagePath = "/galaxyS21.jpg",
                            IsArchived = false,
                            Name = "Samsung Galaxy S21",
                            Price = 1249.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 16,
                            AverageRating = 0.0,
                            BrandId = 3,
                            Description = "This is fluff for now",
                            ImagePath = "/pixel3.jpg",
                            IsArchived = false,
                            Name = "Pixel 3",
                            Price = 799.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 17,
                            AverageRating = 0.0,
                            BrandId = 3,
                            Description = "This is fluff for now",
                            ImagePath = "/pixel4.jpg",
                            IsArchived = false,
                            Name = "Pixel 4",
                            Price = 869.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 18,
                            AverageRating = 0.0,
                            BrandId = 3,
                            Description = "This is fluff for now",
                            ImagePath = "/pixel5.jpg",
                            IsArchived = false,
                            Name = "Pixel 5",
                            Price = 929.99m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ReviewIT.DataAccess.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NickName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "63062",
                            CreationDate = new DateTime(2020, 2, 27, 21, 13, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "npeedell0@howstuffworks.com",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Bytrxa8980",
                            PasswordHash = "AQAAAAEAACcQAAAAEGoXSEkWUu0jowjLG6p7gUnxysrgWdglb7qB3mp9amSJw4Y5rvPqKhDo11DSd2JppA=="
                        },
                        new
                        {
                            UserId = "83912",
                            CreationDate = new DateTime(2020, 7, 30, 3, 8, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mborrett1@google.cn",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Zxbcdq4196",
                            PasswordHash = "AQAAAAEAACcQAAAAEISBV6ylpl+pyZphD91uplpIB9VUWfpM6MtUevbUhgAy+JbCK/PNr5su5t34OthPHg=="
                        },
                        new
                        {
                            UserId = "77416",
                            CreationDate = new DateTime(2020, 4, 22, 18, 44, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "gmacrury2@facebook.com",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Htdkzb1212",
                            PasswordHash = "AQAAAAEAACcQAAAAECffeqvrSVRq7+dQVIcsWl7qFDLJ5vBN2hu+fHe4Ehufd2cZAle/uHSYp4+Q9tFEcw=="
                        },
                        new
                        {
                            UserId = "42923",
                            CreationDate = new DateTime(2018, 5, 21, 5, 14, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bbyrne3@reverbnation.com",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Kyxfcn8147",
                            PasswordHash = "KNiWZVMh"
                        },
                        new
                        {
                            UserId = "79354",
                            CreationDate = new DateTime(2019, 1, 15, 7, 24, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kvillage4@census.gov",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Hdrvya8006",
                            PasswordHash = "IcgWFtGC"
                        },
                        new
                        {
                            UserId = "78347",
                            CreationDate = new DateTime(2019, 5, 31, 0, 37, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "chuggill5@flickr.com",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Wifrmn8717",
                            PasswordHash = "OlXbLqtXJfK"
                        },
                        new
                        {
                            UserId = "6561",
                            CreationDate = new DateTime(2020, 11, 8, 9, 44, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "pbockin6@hugedomains.com",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Thusls4964",
                            PasswordHash = "tBPWKuaj9N"
                        },
                        new
                        {
                            UserId = "4345",
                            CreationDate = new DateTime(2020, 3, 24, 18, 34, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ntrimbey7@blog.com",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Hmsffu2509",
                            PasswordHash = "HlNiWB"
                        },
                        new
                        {
                            UserId = "67588",
                            CreationDate = new DateTime(2019, 6, 24, 14, 37, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mskedge8@blog.com",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Wlgtgm9390",
                            PasswordHash = "v6eGUm8f"
                        },
                        new
                        {
                            UserId = "26600",
                            CreationDate = new DateTime(2019, 3, 21, 3, 35, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "wkasman9@homestead.com",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Jilfpv3327",
                            PasswordHash = "JH9HVJs3Z0B"
                        },
                        new
                        {
                            UserId = "61437",
                            CreationDate = new DateTime(2020, 10, 11, 11, 2, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "pswetta@blogger.com",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Khqcgy0148",
                            PasswordHash = "Jd2kLQ"
                        },
                        new
                        {
                            UserId = "85497",
                            CreationDate = new DateTime(2020, 11, 2, 23, 10, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bhessayb@cisco.com",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Zttafw0061",
                            PasswordHash = "FgHq8ir"
                        },
                        new
                        {
                            UserId = "21564",
                            CreationDate = new DateTime(2019, 4, 13, 10, 8, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "klawriec@ucoz.ru",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Xtyfpx1524",
                            PasswordHash = "gTTP0LBwRH"
                        },
                        new
                        {
                            UserId = "73398",
                            CreationDate = new DateTime(2020, 7, 9, 6, 34, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bkilleend@yahoo.co.jp",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Hvmema7791",
                            PasswordHash = "q1IJj55"
                        },
                        new
                        {
                            UserId = "67706",
                            CreationDate = new DateTime(2019, 4, 1, 16, 27, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ocoselye@jalbum.net",
                            IsAdmin = false,
                            IsArchived = false,
                            NickName = "Iafqzl3913",
                            PasswordHash = "sWEDyx35s"
                        },
                        new
                        {
                            UserId = "admin",
                            CreationDate = new DateTime(2019, 4, 1, 16, 27, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "admin@admin.admin",
                            IsAdmin = true,
                            IsArchived = false,
                            NickName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEEViKHj5p9eE8g8LKuNpezIep9S4K75RXujhlWbFDwH1FTiW+3AUEP9oBXgjvlgKIQ=="
                        });
                });

            modelBuilder.Entity("ReviewIT.DataAccess.Comment", b =>
                {
                    b.HasOne("ReviewIT.DataAccess.Comment", null)
                        .WithMany("ChildComments")
                        .HasForeignKey("CommentId1");

                    b.HasOne("ReviewIT.DataAccess.User", "CreatorUser")
                        .WithMany("Comments")
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("ReviewIT.DataAccess.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReviewIT.DataAccess.CommentVote", b =>
                {
                    b.HasOne("ReviewIT.DataAccess.Comment", "Comment")
                        .WithMany("CommentVotes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReviewIT.DataAccess.User", "User")
                        .WithMany("CommentVotes")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ReviewIT.DataAccess.Post", b =>
                {
                    b.HasOne("ReviewIT.DataAccess.User", "CreatorUser")
                        .WithMany("Posts")
                        .HasForeignKey("CreatorUserId");
                });

            modelBuilder.Entity("ReviewIT.DataAccess.PostVote", b =>
                {
                    b.HasOne("ReviewIT.DataAccess.Post", "Post")
                        .WithMany("PostVotes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReviewIT.DataAccess.User", "User")
                        .WithMany("PostVotes")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ReviewIT.DataAccess.Product", b =>
                {
                    b.HasOne("ReviewIT.DataAccess.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
